# Copyright (C) 2017-2021 The LineageOS Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/samsung/exynos5420-common/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/samsung/exynos5420-common/proprietary/bin/cs:system/bin/cs \
    vendor/samsung/exynos5420-common/proprietary/bin/gpsd:system/bin/gpsd \
    vendor/samsung/exynos5420-common/proprietary/bin/mcDriverDaemon:system/bin/mcDriverDaemon \
    vendor/samsung/exynos5420-common/proprietary/lib/hw/gps.universal5420.so:system/lib/hw/gps.universal5420.so \
    vendor/samsung/exynos5420-common/proprietary/lib/libGLES_trace.so:system/lib/libGLES_trace.so \
    vendor/samsung/exynos5420-common/proprietary/lib/libMcClient.so:system/lib/libMcClient.so \
    vendor/samsung/exynos5420-common/proprietary/lib/libMcRegistry.so:system/lib/libMcRegistry.so \
    vendor/samsung/exynos5420-common/proprietary/lib/libaptX_encoder.so:system/lib/libaptX_encoder.so \
    vendor/samsung/exynos5420-common/proprietary/lib/libexynoscamera.so:system/lib/libexynoscamera.so \
    vendor/samsung/exynos5420-common/proprietary/lib/libfloatingfeature.so:system/lib/libfloatingfeature.so \
    vendor/samsung/exynos5420-common/proprietary/lib/libvdis.so:system/lib/libvdis.so \
    vendor/samsung/exynos5420-common/proprietary/lib/omx/libOMX.Exynos.AVC.Encoder.so:system/lib/omx/libOMX.Exynos.AVC.Encoder.so \
    vendor/samsung/exynos5420-common/proprietary/vendor/bin/hw/android.hardware.drm@1.1-service.widevine:$(TARGET_COPY_OUT_VENDOR)/bin/hw/android.hardware.drm@1.1-service.widevine \
    vendor/samsung/exynos5420-common/proprietary/vendor/etc/init/android.hardware.drm@1.1-service.widevine.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.drm@1.1-service.widevine.rc \
    vendor/samsung/exynos5420-common/proprietary/vendor/firmware/mfc_fw.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/mfc_fw.bin \
    vendor/samsung/exynos5420-common/proprietary/vendor/firmware/srp_cga.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/srp_cga.bin \
    vendor/samsung/exynos5420-common/proprietary/vendor/firmware/srp_data.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/srp_data.bin \
    vendor/samsung/exynos5420-common/proprietary/vendor/firmware/srp_vliw.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/srp_vliw.bin \
    vendor/samsung/exynos5420-common/proprietary/vendor/lib/egl/libGLES_mali.so:$(TARGET_COPY_OUT_VENDOR)/lib/egl/libGLES_mali.so \
    vendor/samsung/exynos5420-common/proprietary/vendor/lib/libRSDriverArm.so:$(TARGET_COPY_OUT_VENDOR)/lib/libRSDriverArm.so \
    vendor/samsung/exynos5420-common/proprietary/vendor/lib/soundfx/liblvverx.so:$(TARGET_COPY_OUT_VENDOR)/lib/soundfx/liblvverx.so \
    vendor/samsung/exynos5420-common/proprietary/vendor/lib/soundfx/liblvvetx.so:$(TARGET_COPY_OUT_VENDOR)/lib/soundfx/liblvvetx.so \
    vendor/samsung/exynos5420-common/proprietary/vendor/lib/libmalicore.bc:$(TARGET_COPY_OUT_VENDOR)/lib/libmalicore.bc \
    vendor/samsung/exynos5420-common/proprietary/vendor/lib/libstlport.so:$(TARGET_COPY_OUT_VENDOR)/lib/libstlport.so \
    vendor/samsung/exynos5420-common/proprietary/vendor/lib/libwvhidl.so:$(TARGET_COPY_OUT_VENDOR)/lib/libwvhidl.so \
    vendor/samsung/exynos5420-common/proprietary/vendor/lib/mediadrm/libwvdrmengine.so:$(TARGET_COPY_OUT_VENDOR)/lib/mediadrm/libwvdrmengine.so
