# Copyright (C) 2017-2021 The LineageOS Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/samsung/chagall-common/setup-makefiles.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/samsung/chagall-common

PRODUCT_COPY_FILES += \
    vendor/samsung/chagall-common/proprietary/vendor/app/FFFFFFFF000000000000000000000001.drbin:$(TARGET_COPY_OUT_VENDOR)/app/FFFFFFFF000000000000000000000001.drbin \
    vendor/samsung/chagall-common/proprietary/vendor/app/mcRegistry/00060308060501020000000000000000.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/00060308060501020000000000000000.tlbin \
    vendor/samsung/chagall-common/proprietary/vendor/app/mcRegistry/02010000080300030000000000000000.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/02010000080300030000000000000000.tlbin \
    vendor/samsung/chagall-common/proprietary/vendor/app/mcRegistry/07010000000000000000000000000000.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/07010000000000000000000000000000.tlbin \
    vendor/samsung/chagall-common/proprietary/vendor/app/mcRegistry/07060000000000000000000000000000.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/07060000000000000000000000000000.tlbin \
    vendor/samsung/chagall-common/proprietary/vendor/app/mcRegistry/08130000000000000000000000000000.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/08130000000000000000000000000000.tlbin \
    vendor/samsung/chagall-common/proprietary/vendor/app/mcRegistry/ffffffff000000000000000000000003.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/ffffffff000000000000000000000003.tlbin \
    vendor/samsung/chagall-common/proprietary/vendor/app/mcRegistry/ffffffff000000000000000000000004.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/ffffffff000000000000000000000004.tlbin \
    vendor/samsung/chagall-common/proprietary/vendor/app/mcRegistry/ffffffff000000000000000000000005.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/ffffffff000000000000000000000005.tlbin \
    vendor/samsung/chagall-common/proprietary/vendor/app/mcRegistry/ffffffff000000000000000000000007.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/ffffffff000000000000000000000007.tlbin \
    vendor/samsung/chagall-common/proprietary/vendor/app/mcRegistry/ffffffff000000000000000000000008.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/ffffffff000000000000000000000008.tlbin \
    vendor/samsung/chagall-common/proprietary/vendor/app/mcRegistry/ffffffff000000000000000000000009.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/ffffffff000000000000000000000009.tlbin \
    vendor/samsung/chagall-common/proprietary/vendor/app/mcRegistry/ffffffff00000000000000000000000a.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/ffffffff00000000000000000000000a.tlbin \
    vendor/samsung/chagall-common/proprietary/vendor/app/mcRegistry/ffffffff00000000000000000000000c.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/ffffffff00000000000000000000000c.tlbin \
    vendor/samsung/chagall-common/proprietary/vendor/app/mcRegistry/ffffffff00000000000000000000000d.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/ffffffff00000000000000000000000d.tlbin \
    vendor/samsung/chagall-common/proprietary/vendor/app/mcRegistry/ffffffff00000000000000000000000e.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/ffffffff00000000000000000000000e.tlbin \
    vendor/samsung/chagall-common/proprietary/vendor/app/mcRegistry/ffffffff00000000000000000000000f.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/ffffffff00000000000000000000000f.tlbin \
    vendor/samsung/chagall-common/proprietary/vendor/app/mcRegistry/ffffffff000000000000000000000010.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/ffffffff000000000000000000000010.tlbin \
    vendor/samsung/chagall-common/proprietary/vendor/app/mcRegistry/ffffffff000000000000000000000011.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/ffffffff000000000000000000000011.tlbin \
    vendor/samsung/chagall-common/proprietary/vendor/app/mcRegistry/ffffffff000000000000000000000012.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/ffffffff000000000000000000000012.tlbin \
    vendor/samsung/chagall-common/proprietary/vendor/app/mcRegistry/ffffffff000000000000000000000013.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/ffffffff000000000000000000000013.tlbin \
    vendor/samsung/chagall-common/proprietary/vendor/app/mcRegistry/ffffffff000000000000000000000017.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/ffffffff000000000000000000000017.tlbin \
    vendor/samsung/chagall-common/proprietary/vendor/app/mcRegistry/ffffffff000000000000000000000018.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/ffffffff000000000000000000000018.tlbin \
    vendor/samsung/chagall-common/proprietary/vendor/app/mcRegistry/ffffffff000000000000000000000041.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/ffffffff000000000000000000000041.tlbin \
    vendor/samsung/chagall-common/proprietary/vendor/app/mcRegistry/ffffffffd00000000000000000000004.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/ffffffffd00000000000000000000004.tlbin \
    vendor/samsung/chagall-common/proprietary/vendor/app/mcRegistry/ffffffffd0000000000000000000000a.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/ffffffffd0000000000000000000000a.tlbin \
    vendor/samsung/chagall-common/proprietary/vendor/app/mcRegistry/ffffffffd0000000000000000000000e.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/ffffffffd0000000000000000000000e.tlbin \
    vendor/samsung/chagall-common/proprietary/vendor/app/mcRegistry/fffffffff0000000000000000000001e.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/fffffffff0000000000000000000001e.tlbin \
    vendor/samsung/chagall-common/proprietary/vendor/bin/vcsFPService:$(TARGET_COPY_OUT_VENDOR)/bin/vcsFPService \
    vendor/samsung/chagall-common/proprietary/etc/wifi/bcmdhd_apsta.bin:$(TARGET_COPY_OUT_SYSTEM)/etc/wifi/bcmdhd_apsta.bin \
    vendor/samsung/chagall-common/proprietary/etc/wifi/bcmdhd_apsta.bin_4354_a0:$(TARGET_COPY_OUT_SYSTEM)/etc/wifi/bcmdhd_apsta.bin_4354_a0 \
    vendor/samsung/chagall-common/proprietary/etc/wifi/bcmdhd_apsta.bin_4354_a1:$(TARGET_COPY_OUT_SYSTEM)/etc/wifi/bcmdhd_apsta.bin_4354_a1 \
    vendor/samsung/chagall-common/proprietary/etc/wifi/bcmdhd_ibss.bin:$(TARGET_COPY_OUT_SYSTEM)/etc/wifi/bcmdhd_ibss.bin \
    vendor/samsung/chagall-common/proprietary/etc/wifi/bcmdhd_ibss.bin_4354_a0:$(TARGET_COPY_OUT_SYSTEM)/etc/wifi/bcmdhd_ibss.bin_4354_a0 \
    vendor/samsung/chagall-common/proprietary/etc/wifi/bcmdhd_ibss.bin_4354_a1:$(TARGET_COPY_OUT_SYSTEM)/etc/wifi/bcmdhd_ibss.bin_4354_a1 \
    vendor/samsung/chagall-common/proprietary/etc/wifi/bcmdhd_mfg.bin:$(TARGET_COPY_OUT_SYSTEM)/etc/wifi/bcmdhd_mfg.bin \
    vendor/samsung/chagall-common/proprietary/etc/wifi/bcmdhd_mfg.bin_4354_a0:$(TARGET_COPY_OUT_SYSTEM)/etc/wifi/bcmdhd_mfg.bin_4354_a0 \
    vendor/samsung/chagall-common/proprietary/etc/wifi/bcmdhd_mfg.bin_4354_a1:$(TARGET_COPY_OUT_SYSTEM)/etc/wifi/bcmdhd_mfg.bin_4354_a1 \
    vendor/samsung/chagall-common/proprietary/etc/wifi/bcmdhd_sta.bin:$(TARGET_COPY_OUT_SYSTEM)/etc/wifi/bcmdhd_sta.bin \
    vendor/samsung/chagall-common/proprietary/etc/wifi/bcmdhd_sta.bin_4354_a0:$(TARGET_COPY_OUT_SYSTEM)/etc/wifi/bcmdhd_sta.bin_4354_a0 \
    vendor/samsung/chagall-common/proprietary/etc/wifi/bcmdhd_sta.bin_4354_a1:$(TARGET_COPY_OUT_SYSTEM)/etc/wifi/bcmdhd_sta.bin_4354_a1 \
    vendor/samsung/chagall-common/proprietary/etc/wifi/cred.conf:$(TARGET_COPY_OUT_SYSTEM)/etc/wifi/cred.conf \
    vendor/samsung/chagall-common/proprietary/etc/wifi/nvram_mfg.txt_4354_a0:$(TARGET_COPY_OUT_SYSTEM)/etc/wifi/nvram_mfg.txt_4354_a0 \
    vendor/samsung/chagall-common/proprietary/etc/wifi/nvram_mfg.txt_4354_a1:$(TARGET_COPY_OUT_SYSTEM)/etc/wifi/nvram_mfg.txt_4354_a1 \
    vendor/samsung/chagall-common/proprietary/etc/wifi/nvram_net.txt_4354_a0:$(TARGET_COPY_OUT_SYSTEM)/etc/wifi/nvram_net.txt_4354_a0 \
    vendor/samsung/chagall-common/proprietary/etc/wifi/nvram_net.txt_4354_a1:$(TARGET_COPY_OUT_SYSTEM)/etc/wifi/nvram_net.txt_4354_a1 \
    vendor/samsung/chagall-common/proprietary/vendor/lib/sensors.universal5420.so:$(TARGET_COPY_OUT_VENDOR)/lib/sensors.universal5420.so \
    vendor/samsung/chagall-common/proprietary/vendor/lib/libak09911c.so:$(TARGET_COPY_OUT_VENDOR)/lib/libak09911c.so \
    vendor/samsung/chagall-common/proprietary/vendor/lib/libfpasmtztransport.so:$(TARGET_COPY_OUT_VENDOR)/lib/libfpasmtztransport.so \
    vendor/samsung/chagall-common/proprietary/vendor/lib/libvalAuth.so:$(TARGET_COPY_OUT_VENDOR)/lib/libvalAuth.so \
    vendor/samsung/chagall-common/proprietary/vendor/lib/libvcsfp.so:$(TARGET_COPY_OUT_VENDOR)/lib/libvcsfp.so \
    vendor/samsung/chagall-common/proprietary/vendor/lib/libvfmClient.so:$(TARGET_COPY_OUT_VENDOR)/lib/libvfmClient.so \
    vendor/samsung/chagall-common/proprietary/vendor/lib/libvfmtztransport.so:$(TARGET_COPY_OUT_VENDOR)/lib/libvfmtztransport.so \
    vendor/samsung/chagall-common/proprietary/vendor/firmware/bcm4350_V0301.0609.hcd:$(TARGET_COPY_OUT_VENDOR)/firmware/bcm4350_V0301.0609.hcd \
    vendor/samsung/chagall-common/proprietary/vendor/firmware/fimc_is_fw2_IMX134_EEPROM.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/fimc_is_fw2_IMX134_EEPROM.bin \
    vendor/samsung/chagall-common/proprietary/vendor/firmware/setfile_6b2_eeprom.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/setfile_6b2_eeprom.bin \
    vendor/samsung/chagall-common/proprietary/vendor/firmware/setfile_imx134_eeprom.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/setfile_imx134_eeprom.bin
